version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - gobank
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  gobank:
    driver: bridge

volumes:
  postgres-data:
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
