openapi: 3.0.3
info:
  title: mybank
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost:3000
paths:
  /api/v1/accounts:
    get:
      tags:
        - Accounts
      summary: List accounts
      description: List accounts
      operationId: listAccounts
      parameters:
        - name: page_id
          in: query
          schema:
            type: string
            example: '1'
        - name: page_size
          in: query
          schema:
            type: string
            example: '5'
      responses:
        '200':
          description: ''
    post:
      tags:
        - Accounts
      summary: Create account
      description: Create account
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency:
                  type: string
                  example: CAD
            example:
              currency: CAD
      responses:
        '200':
          description: ''
  /api/v1/accounts/{id}:
    get:
      tags:
        - Accounts
      summary: Get account
      description: Get account
      operationId: getAccount
      responses:
        '200':
          description: ''
    delete:
      tags:
        - Accounts
      summary: Delete account
      description: Delete account
      operationId: deleteAccount
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: '125'
  /api/v1/accounts/{id}/balance:
    post:
      tags:
        - Accounts
      summary: Add balance
      description: Add balance
      operationId: addBalance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example: {}
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: '1'
  /api/v1/transfers:
    post:
      tags:
        - Transfers
      summary: Create transfer
      description: Create transfer
      operationId: createTransfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 10
                currency:
                  type: string
                  example: CAD
                from_account_id:
                  type: number
                  example: 17
                to_account_id:
                  type: number
                  example: 16
            example:
              amount: 10
              currency: CAD
              from_account_id: 17
              to_account_id: 16
      responses:
        '200':
          description: ''
  /api/v1/users:
    post:
      tags:
        - Users
      summary: Create user
      description: Create user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: asd@asd.ceom
                full_name:
                  type: string
                  example: banker
                password:
                  type: string
                  example: qweqwe
                username:
                  type: string
                  example: banke43r
            example:
              email: asd@asd.ceom
              full_name: banker
              password: qweqwe
              username: banke43r
      responses:
        '200':
          description: ''
  /api/v1/users/login:
    post:
      tags:
        - Users
      summary: Login user
      description: Login user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: banker123
                username:
                  type: string
                  example: banker
            example:
              password: banker123
              username: banker
      responses:
        '200':
          description: ''
  /api/v1/users/renew_access:
    post:
      tags:
        - Users
      summary: Renew token
      description: Renew token
      operationId: renewToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  example: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYzRiYWYyLTlhYmUtNDU3Yy05MDU0LWIwM2JlMGFhMDFmZCIsInVzZXJuYW1lIjoibWFyY28xMjMiLCJyb2xlIjoiZGVwb3NpdG9yIiwiaXNzdWVkX2F0IjoiMjAyNC0wNS0yOVQyMzo1OTo1MS40MTEzMDE1KzAxOjAwIiwiZXhwaXJlZF9hdCI6IjIwMjQtMDUtMzBUMjM6NTk6NTEuNDExMzAxNSswMTowMCJ9.8lxNtIC9UwwP-Z2CLdpLq3ayLRxYed40L_f1FX9xGkY
            example:
              refresh_token: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYzRiYWYyLTlhYmUtNDU3Yy05MDU0LWIwM2JlMGFhMDFmZCIsInVzZXJuYW1lIjoibWFyY28xMjMiLCJyb2xlIjoiZGVwb3NpdG9yIiwiaXNzdWVkX2F0IjoiMjAyNC0wNS0yOVQyMzo1OTo1MS40MTEzMDE1KzAxOjAwIiwiZXhwaXJlZF9hdCI6IjIwMjQtMDUtMzBUMjM6NTk6NTEuNDExMzAxNSswMTowMCJ9.8lxNtIC9UwwP-Z2CLdpLq3ayLRxYed40L_f1FX9xGkY
      responses:
        '200':
          description: ''
  /api/v1/users/{username}:
    patch:
      tags:
        - Users
      summary: Update user
      description: Update user
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: banker@gmail.com
                full_name:
                  type: string
                  example: bankeiro do gmail
                password:
                  type: string
                  example: banker123
            example:
              email: banker@gmail.com
              full_name: bankeiro do gmail
              password: banker123
      responses:
        '200':
          description: ''
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
          example: banker
tags:
  - name: Accounts
  - name: Transfers
  - name: Users
